spring:
  application:
    name: 'helpdesk-bff'
  cloud:
    config:
      uri: 'config-server'
      name: 'helpdesk-bff'
eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
springdoc:
  openapi:
    title: 'BFF Helpdesk API'
    description: 'Component responsible for agregating the microservices of HelpDesk'
    version: '1.0.0'